#!/bin/bash
### ---
### name: 'BWA_ALIGN (aligning NA12878)'
### container: 'biocontainers/bwa:v0.7.17_cv1'
### outputs:
### - 'NA12878.sam'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/ba/51e1186307bd57a844d41fda887011/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 1024 -e "NXF_TASK_WORKDIR" -v /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline:/Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline -w "$NXF_TASK_WORKDIR" --platform linux/amd64 --name $NXF_BOXID biocontainers/bwa:v0.7.17_cv1 /bin/bash -ue /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/ba/51e1186307bd57a844d41fda887011/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f chr17.fa.bwt
    rm -f chr17.fa
    rm -f NA12878_chr17_1.fastq
    rm -f NA12878_chr17_2.fastq
    rm -f chr17.fa.amb
    rm -f chr17.fa.ann
    rm -f chr17.fa.pac
    rm -f chr17.fa.sa
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/43/b65273283eeb77a426cd3ab45d7352/chr17.fa.bwt chr17.fa.bwt
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/data/chr17.fa chr17.fa
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/data/NA12878_chr17_1.fastq NA12878_chr17_1.fastq
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/data/NA12878_chr17_2.fastq NA12878_chr17_2.fastq
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/43/b65273283eeb77a426cd3ab45d7352/chr17.fa.amb chr17.fa.amb
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/43/b65273283eeb77a426cd3ab45d7352/chr17.fa.ann chr17.fa.ann
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/43/b65273283eeb77a426cd3ab45d7352/chr17.fa.pac chr17.fa.pac
    ln -s /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/43/b65273283eeb77a426cd3ab45d7352/chr17.fa.sa chr17.fa.sa
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/gizem/Desktop/biyoinformatik_projeler/ngs-variant-calling-pipeline/nextflow_pipeline/work/ba/51e1186307bd57a844d41fda887011/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
